#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Changing lastmod and modifiedAt metadata'

git diff --cached --name-only --diff-filter=ACM -z -- content/ | xargs -0 echo

# If everything passes... Now we can commit
echo '✅ Everything looks good. Creating commit... ✅'
